// Writes ../CREDITS.md from the asset manifests (every scanned asset with author,
// source link and licence) plus the vendored libraries.
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const j = (p) => JSON.parse(readFileSync(join(root, p), 'utf8'));
const mm = j('assets/manifest-models.json'), tm = j('assets/manifest-textures.json'), sky = j('assets/sky/skies.json');
const rows = [];
const add = (src, what) => { if (src) rows.push({ ...src, what }); };
for (const m of Object.values(mm.models || mm)) for (const src of m.sources || [m.source]) add(src, m.kind === 'characters' ? 'characters' : m.kind === 'animations' ? 'animation' : 'model');
for (const [sec, what] of [['textures', 'material'], ['atlases', 'foliage atlas'], ['decals', 'decal']]) for (const t of Object.values(tm[sec] || {})) add(t.source, what);
for (const s of Object.values(sky)) add(s.source, 'sky (HDRI)');
const seen = new Set();
const list = rows.filter((r) => (seen.has(r.url) ? false : seen.add(r.url))).sort((a, b) => (a.source + a.name).localeCompare(b.source + b.name));
const section = (src) => list.filter((r) => r.source === src || (src === 'ambientCG' && /ambientCG/.test(r.source))).map((r) => `- [${r.name || r.url}](${r.url}) — ${(r.authors || []).join(', ') || 'see source'} — ${r.what} — ${r.license}`).join('\n');
const md = `# Credits and licences

Generated by \`tools/credits.mjs\` from the asset manifests. The same list is shown
in-game under *Credits & licences*.

All scanned models, materials, foliage atlases and sky photographs, the character
bodies, outfits and hairstyles and the animation library are **CC0 1.0 (public
domain)**. Buildings, colony structures, gear, trees, grass placement and terrain
are procedural (generated by this project's code).

## Quaternius (quaternius.com)

${section('Quaternius')}

## Poly Haven (polyhaven.com)

${section('Poly Haven')}

## ambientCG (ambientcg.com)

${section('ambientCG')}

## Libraries (vendored in \`vendor/\`)

- three.js r186.1 — MIT — https://threejs.org
- postprocessing 6.39.5 — zlib — https://github.com/pmndrs/postprocessing
- N8AO 2.0.1 — CC0 — https://github.com/N8python/n8ao
- Basis Universal transcoder (via three.js) — Apache 2.0 — https://github.com/BinomialLLC/basis_universal
- meshoptimizer decoder (via three.js) — MIT — https://github.com/zeux/meshoptimizer

## Fonts

- Barlow and Barlow Condensed (Google Fonts) — SIL Open Font License 1.1
`;
writeFileSync(join(root, 'CREDITS.md'), md);
console.log(`CREDITS.md: ${list.length} assets`);
